baseURL = 'https://litongdeng.github.io/'
locale = 'en-us'
title = 'Litong Deng'

[params]
    blurb = "Hi! I’m Litong, a junior at UC Berkeley double majoring in applied mathematics and public health, with a minor in journalism. I’m currently a Dow Jones News Fund multiplatform editing intern at the San Francisco Chronicle and deputy night editor at The Daily Californian. "