baseURL = 'https://litongdeng.github.io/'
locale = 'en-us'
title = 'Litong Deng'

[params]
    blurb = "Hi! I’m Litong, a junior at UC Berkeley double majoring in applied mathematics and public health, with a minor in journalism. I’m currently a deputy night editor and senior staff reporter at The Daily Californian."